### PR TITLE
Update Views.class.php

### PR DESCRIPTION
**Pull request by rowright**
Switches $form_id to :form_id in binding

### CODE REVIEW

**Comment by rowright** [comment]
References #783 stack trace

**Comment by eharvey71** [comment]
I installed this using Softaculous on Hostgator and was getting "Fatal error: Uncaught PDOException: SQLSTATE[HY093]: Invalid parameter number". Making this correction fixed the issue. When do you think the newest version will get deployed? The version that it installs is 2 years old. Thank you!

**Comment by the-ft** [comment]
really nice project but many little careless misdtakes.
found this too..
views.class.php 911
`                WHERE  v.form_id = $form_id AND`
->
`                WHERE  v.form_id = :form_id AND`
also
Database.class.php 71
`		$this->statement = $this->dbh->prepare($query);`

which have to be sometimes prepare and sometimes query, a quick and dirty approach would be
->
`		if (strpos($query, " :")) {
			$this->statement = $this->dbh->prepare($query);
		} else {
			$this->statement = $this->dbh->query($query);
		}
`

**Comment by benkeen** [comment]
It's an old project now! I haven't been maintaining it for a few years, but given that people are still using it and it's not compatible with PHP8 I'll take some time in the next few months to add PHP8 support. This fix will get rolled out with the next update. Thanks @rowright!

**Pull request merged**
